//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunchbox.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lunchbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Folder/File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnDirOrFile {
            get {
                return ResourceManager.GetString("ColumnDirOrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnPath {
            get {
                return ResourceManager.GetString("ColumnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnPos {
            get {
                return ResourceManager.GetString("ColumnPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirOrFileDir {
            get {
                return ResourceManager.GetString("DirOrFileDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirOrFileFile {
            get {
                return ResourceManager.GetString("DirOrFileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今のが【10回目】の自動起動でした！\nもうマンモーニは卒業です！\nDropbox連携機能が解除されましたので、使ってみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level10 {
            get {
                return ResourceManager.GetString("Level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今のが【20回目】の自動起動でした！\nあんたも成長したもんだ。\n自爆機能が解除されましたので、使ってみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level20 {
            get {
                return ResourceManager.GetString("Level20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosBottomLeft {
            get {
                return ResourceManager.GetString("PosBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosBottomRight {
            get {
                return ResourceManager.GetString("PosBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosDefault {
            get {
                return ResourceManager.GetString("PosDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosTopLeft {
            get {
                return ResourceManager.GetString("PosTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosTopRight {
            get {
                return ResourceManager.GetString("PosTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Del に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
    }
}
